### ISSUE TITLE
Allow library usage

### ISSUE THREAD

**Issue by ernsheong** [itzg/restify#1]
Hi there! Thanks for this. Do consider exposing the logic so that it can be called from other Go code, not just from CLI

**Comment by itzg** [comment]
Great idea. I'll start giving this some thought, but should be quite doable.

**Comment by ernsheong** [comment]
Looking forward to it!

**Comment by itzg** [comment]
It is now library-fied:

https://pkg.go.dev/github.com/itzg/restify@v1.4.0#section-documentation

**Comment by ernsheong** [comment]
Amazing. Thanks and will give it a go really soon in one of my projects :)

**Comment by ernsheong** [comment]
It works! Thanks a lot 👍
